name: Build and Push Docker Images Both Repositories

on:
  workflow_dispatch:

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build DDNet-Server docker image with own Dockerfile (./main/Dockerfile-dockerize special for this repo)
        run: cd main && docker build -t ddnet -f ./Dockerfile-dockerize .

      - name: Tag and Push Docker Image to DockerHub
        run: docker tag ddnet ${{ secrets.DOCKER_USERNAME }}/ddnet

      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ddnet
